In [1]:
from osgeo import gdal
print("done with gdal")
import geopandas as gpd
import pandas as pd

done with gdal


In [2]:

import numpy as np
import copy
import sys
import math

import matplotlib.pyplot as plt

import imageio.v2 as imageio

from osgeo import gdal
#import gdal



In [3]:
def mm_grid(num_levels):
  print(' levels ',num_levels)
  d = int((4**(num_levels))**0.5)
  print('d ',d)
  mort_grid = np.zeros([d, d], dtype = int)
  print(mort_grid,d)
  return mort_grid,d

In [4]:
def intersperse(first,second):
    min_len = min(len(first), len(second))
    return "".join([first[i] + second[i] for i in range(min_len)]) + first[min_len:] + second[min_len:]

In [5]:
def morton1(mort_grid,d):
  # set morton numbers in grid
  for i in range(0,d):
    for j in range(0,d):
      b_row = bin(i)[2:].zfill(d)
      b_col = bin(j)[2:].zfill(d)
      bin_cell = intersperse(b_row,b_col)
      #bin_cell = intersperse(bin(j)[2:],bin(i)[2:])
      mort_grid[i,j] = int(bin_cell, 2)
  return mort_grid

In [6]:
import string
def func_int_bin(x,d):

  bin_lst = []
  b_grid = np.zeros((d,d), dtype='str')
  for i in range(d):
    for j in range(d):
        bb = bin(x[i,j])
        bb = (bb[2:].zfill(d))
        #print(bb)
        # for k in range(d):
        #   #b_grid[i,j] = [k for k in bb[k]]
        test = [x for x in bb]
        my_bin = ''.join(test)
        bin_lst.append(my_bin)

  return(bin_lst)

In [7]:
n_levels = int(8)
mg,d = mm_grid(n_levels)
int_grid = morton1(mg,d)
print(int_grid)
print('')
# bin_lst = func_int_bin(int_grid,d)
# np_bin = np.array(bin_lst)
# print(np_bin.reshape(d, d))
#nw_bin = pd.DataFrame(np_bin, columns=columns, index=index)

 levels  8
d  256
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 256
[[    0     1     4 ... 21841 21844 21845]
 [    2     3     6 ... 21843 21846 21847]
 [    8     9    12 ... 21849 21852 21853]
 ...
 [43682 43683 43686 ... 65523 65526 65527]
 [43688 43689 43692 ... 65529 65532 65533]
 [43690 43691 43694 ... 65531 65534 65535]]

